include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "test/**"
    - "Jules/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    subtype_of_sealed_class: ignore
    must_be_immutable: ignore
    duplicate_ignore: ignore
    unused_import: ignore
    unused_element: ignore
    unused_local_variable: ignore
    unused_field: ignore
    slash_for_doc_comments: ignore
    dangling_library_doc_comments: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    avoid_print: ignore
    deprecated_member_use: ignore
    uri_does_not_exist: ignore
    depend_on_referenced_packages: ignore
    use_build_context_synchronously: ignore
    sized_box_for_whitespace: ignore
    duplicate_import: ignore
    missing_required_argument: ignore
    extra_positional_arguments_could_be_named: ignore
    unnecessary_import: ignore
    unnecessary_cast: ignore
